return {}
-- return {
--   "neovim/nvim-lspconfig",
--   dependencies = { "saghen/blink.cmp" },
--
--   opts = {
--     document_highlight = {
--       enabled = false, -- Disable document highlights
--     },
--   },
-- }
-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       ruff = {
--         -- cmd_env = { RUFF_TRACE = "messages" },
--         init_options = {
--           settings = {
--             logLevel = "debug",
--           },
--         },
--         format = {
--           ["quote-style"] = "single",
--         },
--       },
--     },
--   },
-- }
